import measurementLocations from "@/app/data/measurement-locations.json";
import type {
  LaneMeasurement,
  TrafficSpeedFeature,
  TrafficSpeedFeatureCollection,
} from "@/types/NDW/TrafficSpeed";
import { createCachedFeed } from "../feedCache";
import { asArray, fetchGzipXml } from "./index";

// NDW "snelheden en intensiteiten" feed (trafficspeed.xml.gz): gzipped DATEX II
// MeasuredDataPublication, ~52 MB uncompressed, refreshed every minute.
//
// Each siteMeasurements carries a measurementSiteReference id plus indexed
// measuredValues (TrafficFlow → vehicleFlowRate; TrafficSpeed → averageVehicleSpeed;
// -1 means "no data"). It has no coordinates and no per-index semantics, so both
// come from the static measurement-location table (app/data, generated by
// scripts/generate-measurement-locations.mjs). For each site that table lists
// which indexes hold the aggregate ("anyVehicle") speed (`s`) and flow (`f`).

const FEED_URL = "https://opendata.ndw.nu/trafficspeed.xml.gz";

interface Location {
  c: [number, number];
  // Per-lane aggregate ("anyVehicle") measuredValue indexes: [lane, speedIndex,
  // flowIndex], 0 = not reported. Present on virtually every site.
  m?: [number, number, number][];
  // Fallback flat index lists for the rare site with no per-lane aggregate.
  s?: number[];
  f?: number[];
  n?: string;
  side?: string;
  lanes?: number;
}

const locations = measurementLocations as unknown as Record<string, Location>;

// Read a single measuredValue's numeric value (flow rate or speed), or null.
// biome-ignore lint/suspicious/noExplicitAny: parsed XML is dynamically shaped
function readValue(measuredValue: any): number | null {
  const basicData = measuredValue?.measuredValue?.basicData;
  if (!basicData) return null;
  const raw =
    basicData.vehicleFlow?.vehicleFlowRate ??
    basicData.averageVehicleSpeed?.speed;
  const value = Number(raw);
  // -1 is NDW's "no data" sentinel; drop it along with non-numerics.
  return Number.isFinite(value) && value >= 0 ? value : null;
}

// biome-ignore lint/suspicious/noExplicitAny: parsed XML is dynamically shaped
function toGeoJSON(parsed: any): TrafficSpeedFeatureCollection {
  const sites = asArray(
    parsed?.Envelope?.Body?.d2LogicalModel?.payloadPublication
      ?.siteMeasurements,
  );

  const features: TrafficSpeedFeature[] = [];
  for (const site of sites) {
    const id = site?.measurementSiteReference?.["@_id"];
    const loc = id ? locations[id] : undefined;
    if (!loc) continue;

    // Map this site's measured values by their index.
    const byIndex = new Map<number, number>();
    for (const mv of asArray(site.measuredValue)) {
      const index = Number(mv["@_index"]);
      if (!Number.isFinite(index)) continue;
      const value = readValue(mv);
      if (value !== null) byIndex.set(index, value);
    }

    // Per-lane speed/flow from the aggregate index map, plus the flat values
    // used for the site-level speed (average) and flow (sum).
    const perLane: LaneMeasurement[] = [];
    const speeds: number[] = [];
    const flows: number[] = [];
    if (loc.m?.length) {
      for (const [lane, si, fi] of loc.m) {
        const s = si ? (byIndex.get(si) ?? null) : null;
        const f = fi ? (byIndex.get(fi) ?? null) : null;
        perLane.push({ lane, speed: s, flow: f });
        if (s !== null) speeds.push(s);
        if (f !== null) flows.push(f);
      }
    } else {
      for (const i of loc.s ?? []) {
        const v = byIndex.get(i);
        if (v !== undefined) speeds.push(v);
      }
      for (const i of loc.f ?? []) {
        const v = byIndex.get(i);
        if (v !== undefined) flows.push(v);
      }
    }

    const speed = speeds.length
      ? Math.round(speeds.reduce((a, b) => a + b, 0) / speeds.length)
      : null;
    const flow = flows.length ? flows.reduce((a, b) => a + b, 0) : null;
    if (speed === null && flow === null) continue;

    features.push({
      type: "Feature",
      geometry: { type: "Point", coordinates: loc.c },
      properties: {
        id: String(id),
        name: loc.n,
        side: loc.side,
        lanes: loc.lanes,
        speed,
        flow,
        // Only worth showing a breakdown when there's more than one lane.
        perLane: perLane.length > 1 ? perLane : undefined,
        updateTime: site.measurementTimeDefault,
      },
    });
  }

  return { type: "FeatureCollection", features };
}

const feed = createCachedFeed<TrafficSpeedFeatureCollection>(
  async () => toGeoJSON(await fetchGzipXml(FEED_URL)),
  60_000,
);

// Cached traffic-speed feed as a GeoJSON FeatureCollection. Shared by the tRPC
// procedure (feeds.trafficSpeed); the heavy fetch+parse runs at most once per
// TTL per process.
export const getTrafficSpeed = () => feed.get();
